
ORG 1000H
NUMERO_A_ADIVINAR DB 1,8
COMPARACIONES DB 0,0
;JUGADAS DB 2,3,4,8,1 ;RONDA GANADORA (PARA PROBAR)
JUGADAS DB 2,3,4,8,8,3,3,4,5 ;RONDA PERDEDORA (PARA PROBAR)
RESULT DB ? ;TIENE DIRECCION 1009H SI ES RONDA GANADORA, O 100DH SI ES RONDA PERDERDORA
org 3000h
MATCH: ;EN DL ESTA EL N1
       ;EN DH ESTA EL N2
       PUSH BX
       PUSH AX
       PUSH DX
MOV BX,SP
ADD BX,8
MOV BX,[BX] ;TRAIGO LA DIR. DE POSICION(COMPARACIONES)

IF: CMP DL,DH ;COMPARO SI N1 Y N2 ES IGUAL
    JNZ ELSE ;SI NO ES IGUAL NO HAGO NADA Y SALGO
    MOV BYTE PTR [BX],1 ;PONGO EL VALOR 1 EN LA POSICION
ELSE: POP DX
      POP AX
      POP BX
      RET

ORG 2000H
MOV BX, OFFSET NUMERO_A_ADIVINAR
MOV AX, OFFSET COMPARACIONES
MOV CX, OFFSET JUGADAS
MOV DH, OFFSET RESULT - OFFSET JUGADAS
MOV DL, 0
RONDAS: CMP DL, 8 ;PONGO 8 YA QUE POR CADA COMPARACION VALE 1 Y LA RONDA CUENTA CON 2 COMPARACIONES
        JZ FINCOMPARACION ;SI ES = 8 ENTONCES USO TODAS LAS RONDAS Y LLEGA AL FIN
        CMP DH, 0 ;SI LLEGO AL FINAL DE JUGADAS
        JZ FINCOMPARACION ;NO HAY MAS JUGADA 
        PUSH DX ;GUARDO EN PILA LA CANT DE RONDAS
        PUSH AX ;PUSH LA DIR. DE COMPARACION        
MOV DL,[BX]  ;TRAIGO EL NUMERO A ADIVINAR (N1)
PUSH BX
MOV BX, CX ;EN BX PONGO LA DIR DE JUGADA
MOV DH, [BX] ;TRAIGO EL VALOR DE JUGADA

POP BX ;DEVUELVO EL DIR DE JUGADAS
PUSH DX
CALL MATCH
POP DX ;DEVUELVO LOS N1 Y N2
POP DX ;REEMPLAZO LOS VALORES DE N1 Y N2 PARA GUARDAR EL CONTADOR
POP AX
PUSH BX ;GUARDO NUM A ADIVINAR
MOV BX, AX ; PONGO EN BX LA DIR DE COMPARACION
CMP BYTE PTR [BX], 1 ;COMPARO CON 1 SI ADIVINO EL NUM
JZ SIADIVINO
POP BX
INC CX ; VA A LA SGTE JUGADA
INC DL ; INCREMENTO EL CONTADOR DE RONDAS
DEC DH ; DECREMENTO LA CANTIDAD DE JUGADAS
JMP RONDAS
SIADIVINO: CMP BX, AX ;PREGUNTAMOS SI LLEGO AL FINAL DE LA TABLA DE COMPARACIONES
           JS FINCOMPARACION 
           INC BX ; PASA LA SGTE COMPARACION
           MOV AX, BX; GUARDO LA SGTE COMPARACION
           POP BX
           INC BX ;PASO AL SGTE NUM A COMPARAR YA QUE ADIVINO EL NUM
FINCOMPARACION: PUSH CX
                MOV CL,[BX]
                CMP CL, 1 ;COMPARO SI EL ULTIMO VALOR DE COMPARACION ES UNO
         JZ GANO ; SI ES 1 SIGNIFICA QUE LA TABLA TIENE 1,1 LO QUE SIGNIFICA QUE GANO
         POP CX
         PUSH DX
         MOV DH, 00H; PERDIO ENTONCES PONEMOS 00H
         MOV RESULT, DH ;GUARDA EN RESULTADO
         POP DX
         JMP FIN
GANO: POP CX
      PUSH DX
      MOV DH, 0FFH; GANO ENTONCES PONEMOS 0FFH
      MOV RESULT, DH ;GUARDA EN MEMORIA
      POP DX
      JMP FIN
FIN: HLT
END