
ORG 1000H
TABLAA DB 1,20,5,4,30
CANT DB ?
ORG 3000H
RUTINA: PUSH BX
        PUSH CX
        MOV BX, SP
        ADD BX, 2 
        MOV BX, [BX]
        MOV AL, [BX] ; Traje el numero por ref via pila
        MOV CL, 0; INICIALIZO EL TOTALIZADOR
        MOV CH, 1; INICIALIZO LA CANTIDAD DE VECES QUE HARA
FOR: CMP CH, AL ;COMPARO SI LLEGO AL FIN DEL FOR
     JZ FINRUT ;TERMINA EL FOR 
     ADD CL,CH ;SUMO LA CANT DEL INDICE AL TOTALIZADOR
     INC CH ;INCREMENTO PARA EL SGTE FOR
     JMP FOR       
FINRUT: MOV [BX], CL ;GUARDO EN LA TABLA EL VALOR MODIFICADO
        POP CX
        POP BX
        RET
ORG 2000H
MOV BX, OFFSET TABLAA
MOV CL, OFFSET CANT - OFFSET TABLAA ;OBTENGO LA DIMF DE LA TABLA
MOV CH, 0 ;TOTALIZADOR DE LA CANT DE VECES QUE SE MODIFICO
REALIZA: CMP BYTE PTR [BX], 20 ;COMPARO SI EL VALOR DE LA TABLA ES 20
         JNS SGTEVALOR ;SI ES MAYOR A 20 SIGUE AL SGTE VALOR
         PUSH BX
         PUSH CX
         CALL RUTINA
         POP CX
         POP BX
         INC CH    ;INCREMENTO LA CANTIDAD DE VECES QUE SE MODIFICO EL VALOR
         JMP REALIZA
SGTEVALOR: CMP CL,0  ;COMPARO SI LA CANT DE ELE DE TABLA LLEGO A 0
           JZ FIN    ;SI LLEGO TERMINO LA TABLA
           INC BX    ;AVANZO AL SGTE VALOR
           DEC CL    ;DECREMENTO LA CANT DE ELE  
FIN:  MOV CANT, CH
      HLT
END





