; ¡Bienvenido a VonSim!
;ETIQUETAS   INSTRUCCIONES   COMENTARIOS
			;Inicio de memoria de datos
org 1000h

;N     DW 1
RES   DW 0;DIREC DE MEMORIA DONDE SE VA A GUARDAR EL RESULTADO DEL FACTORIAL
TABLA DW 2,5,4,7,3; COMIENZA EN LA 1002h
TABLA_2 DW 0,0,0,0,0; COMIENZA EN LA 100Ch

org 3000h 
FAC:
      PUSH AX; GUARDAMOS LOS VALORES DE LOS REGIS. DEL PROG. PRINCIPAL
      PUSH CX
      PUSH BX
      PUSH DX
      
      MOV BX, SP
      ADD BX,12; en bx tengo la direc. deL primer elem de la tabla1
      MOV AX,[BX]; copiamos el numero a quien tenemos que hacer el fac
      MOV CX,AX; CX TIENE EL MISMO VALOR QUE AX
      CMP AX,1; ESTE CONSIDERA SI EL VALOR ES 1 
      JZ RESUL
      MOV DX,0
      DEC CX; CX VALE 4 LA PRIMERA VEZ 
      MOV BX,CX 
      JMP SUMA
 
MUL:  POP AX; recuperamos el valor de la suma y lo cpiamos en ax 
      DEC CX
      JZ RESUL  
      MOV BX,CX
      MOV DX,0;iniliacisamos siempre dx que es donde se guarda la suma
      
SUMA: 
      ADD DX,AX;  
      DEC BX
      JNZ SUMA
      PUSH DX; gaardamos el valor de la suma en la pila
      JMP MUL

RESUL:  MOV BX, SP
        ADD BX,10
       MOV BX,[BX]
       MOV [BX],AX; AX TIENE EL RESUL DEL FACTORIAL
       
FIN2: POP DX ; RECUPERAMOS TODOS LOS VALORES DE LOS REGIS. QUE TENIAN ANTES DE ENTRAR A LA SUB_RUTINA
      POP BX
      POP CX
      POP AX
RET    
        
org 2000h; PROGRAMA PRINCIPAL
   MOV AH,0
   MOV AL,OFFSET TABLA_2 - OFFSET TABLA; DIML DE TABLA
   
   MOV CX,OFFSET TABLA
   MOV DX,OFFSET TABLA_2
   
LOOP: 
   PUSH AX;GUARDA LA DIML DE LA TABLA 1
   MOV BX,CX
   MOV AX,[BX];COPIAMOS EL NUM N EN AX     
   PUSH AX
   MOV AX,OFFSET RES
   PUSH AX
   
   CALL FAC
   
   POP AX
   POP AX
   
JMP  COPIAR_RESUL_A_T2
SIGO: 
   ADD CX,2 ;PASAMOS A LA SIGUIENTE POS DE LA TABLA
   POP AX; RECUPERAMOS LA DIML DE LA TABLA 1 
   SUB AX,2 ;DISMINUYE LA DIMF DE TABLA
 
   JNZ LOOP ;SE VA REPETIR TANTAS VECES SEA LA LONG DE LA TABLA 1 
   JMP FIN
   
COPIAR_RESUL_A_T2:  

   MOV AX,RES
   MOV BX,DX
   MOV [BX],AX; RES DEL FAC SE COPIA EN LA PRIMERA POS DE LA TABLA 2
   ADD DX,2
JMP SIGO

   
FIN: HLT
end



